// data/faqData.js

const faqData = [
  {
    question: "How does MockMate personalize my mock interviews?",
    answer:
      "MockMate asks for your job position, skills, and experience to generate questions that match the real-world expectations of your role.",
  },
  {
    question: "What type of feedback do I receive after an interview?",
    answer:
      "After each mock interview, MockMate provides detailed feedback on your answers, highlighting strengths, improvement areas, and offering tips for better performance.",
  },
  {
    question: "Can I practice interviews for different industries or job levels?",
    answer:
      "Yes! MockMate supports a wide range of industries, roles, and experience levels — from entry-level positions to senior leadership roles.",
  },
  {
    question: "Is MockMate free to use?",
    answer:
      "MockMate offers a free trial to help you experience personalized mock interviews. For full access to advanced features and unlimited practice, premium plans are available.",
  },
  {
    question: "How realistic are the mock interviews generated by AI?",
    answer:
      "MockMate's AI is trained on real interview patterns and expert input, ensuring that your practice sessions feel as close to real interviews as possible.",
  },
];

export default faqData;
